<?php

namespace ContainerM0QScek;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FQrwz4eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fQrwz4e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fQrwz4e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'monnaieRepository' => ['privates', 'App\\Repository\\MonnaieRepository', 'getMonnaieRepositoryService', true],
            'paginatorInterface' => ['privates', '.errored.eD2Z7VW', NULL, 'Cannot determine controller argument for "App\\Controller\\MonnaieController::list()": the $paginatorInterface argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
        ], [
            'monnaieRepository' => 'App\\Repository\\MonnaieRepository',
            'paginatorInterface' => '?',
        ]);
    }
}
