<?php

namespace ContainerM0QScek;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LwFJmemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LwFJmem' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LwFJmem'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entrepriseRepository' => ['privates', 'App\\Repository\\EntrepriseRepository', 'getEntrepriseRepositoryService', true],
            'paginatorInterface' => ['privates', '.errored.kB2PJwn', NULL, 'Cannot determine controller argument for "App\\Controller\\EntrepriseController::list()": the $paginatorInterface argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
        ], [
            'entrepriseRepository' => 'App\\Repository\\EntrepriseRepository',
            'paginatorInterface' => '?',
        ]);
    }
}
