<?php

namespace ContainerM0QScek;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3b5fRBXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3b5fRBX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3b5fRBX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'paginatorInterface' => ['privates', '.errored.n8v95EP', NULL, 'Cannot determine controller argument for "App\\Controller\\PaiementPartenaireController::list()": the $paginatorInterface argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'paiementPartenaireRepository' => ['privates', 'App\\Repository\\PaiementPartenaireRepository', 'getPaiementPartenaireRepositoryService', true],
            'partenaireRepository' => ['privates', 'App\\Repository\\PartenaireRepository', 'getPartenaireRepositoryService', true],
            'policeRepository' => ['privates', 'App\\Repository\\PoliceRepository', 'getPoliceRepositoryService', true],
        ], [
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'paginatorInterface' => '?',
            'paiementPartenaireRepository' => 'App\\Repository\\PaiementPartenaireRepository',
            'partenaireRepository' => 'App\\Repository\\PartenaireRepository',
            'policeRepository' => 'App\\Repository\\PoliceRepository',
        ]);
    }
}
