<?php

namespace ContainerM0QScek;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LgVQ4lkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lgVQ4lk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lgVQ4lk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginatorInterface' => ['privates', '.errored.IlKQhpn', NULL, 'Cannot determine controller argument for "App\\Controller\\ProduitController::list()": the $paginatorInterface argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'paginatorInterface' => '?',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
