<?php

namespace ContainerM0QScek;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hg2CPyVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hg2CPyV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hg2CPyV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginatorInterface' => ['privates', '.errored.Yt6tazl', NULL, 'Cannot determine controller argument for "App\\Controller\\PaiementCommissionController::list()": the $paginatorInterface argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'paiementCommissionRepository' => ['privates', 'App\\Repository\\PaiementCommissionRepository', 'getPaiementCommissionRepositoryService', true],
            'partenaireRepository' => ['privates', 'App\\Repository\\PartenaireRepository', 'getPartenaireRepositoryService', true],
            'policeRepository' => ['privates', 'App\\Repository\\PoliceRepository', 'getPoliceRepositoryService', true],
        ], [
            'paginatorInterface' => '?',
            'paiementCommissionRepository' => 'App\\Repository\\PaiementCommissionRepository',
            'partenaireRepository' => 'App\\Repository\\PartenaireRepository',
            'policeRepository' => 'App\\Repository\\PoliceRepository',
        ]);
    }
}
