<?php

namespace ContainerM0QScek;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MelprW7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MelprW7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MelprW7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'paginatorInterface' => ['privates', '.errored.8LQ5snj', NULL, 'Cannot determine controller argument for "App\\Controller\\ClientController::search()": the $paginatorInterface argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
        ], [
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'paginatorInterface' => '?',
        ]);
    }
}
