<?php

namespace ContainerM0QScek;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CId22PwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CId22Pw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CId22Pw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'assureurRepository' => ['privates', 'App\\Repository\\AssureurRepository', 'getAssureurRepositoryService', true],
            'paginatorInterface' => ['privates', '.errored.WEcWtot', NULL, 'Cannot determine controller argument for "App\\Controller\\AssureurController::list()": the $paginatorInterface argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
        ], [
            'assureurRepository' => 'App\\Repository\\AssureurRepository',
            'paginatorInterface' => '?',
        ]);
    }
}
