<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCD7rdcR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCD7rdcR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCD7rdcR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCD7rdcR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCD7rdcR\App_KernelDevDebugContainer([
    'container.build_hash' => 'CD7rdcR',
    'container.build_id' => '5bb572aa',
    'container.build_time' => 1678873213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCD7rdcR');
