<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM0QScek\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM0QScek/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM0QScek.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM0QScek\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM0QScek\App_KernelDevDebugContainer([
    'container.build_hash' => 'M0QScek',
    'container.build_id' => 'caf1633d',
    'container.build_time' => 1678968332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM0QScek');
